### ISSUE TITLE
Reset With a Pin/Button

### ISSUE THREAD

**Issue by adi160885** [gjroots/esp32_nat_router_plus#22]
Is there an option to reset with a Pin/Button, to avoid setting errors such as the reset button mostly on "routers or repeaters/extenders", please provide a solution, thank you in advance sir.

**Comment by adi160885** [comment]
sorry I didn't read everything, your project is very stable for scanning wifi, thank you in advance sir

**Comment by gjroots** [comment]
You're welcome ... 😇
